"""create notes table

Revision ID: d87b74360ed5
Revises: 77932e18cd1d
Create Date: 2020-06-17 16:45:56.099446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87b74360ed5'
down_revision = '77932e18cd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=120), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('notebook_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
