"""create templates table

Revision ID: 357e3e0b27db
Revises: 9601803ca023
Create Date: 2020-06-18 14:46:01.288946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357e3e0b27db'
down_revision = '9601803ca023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('public', sa.Boolean(), nullable=True),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
